### PR TITLE
Add focus cure to paranoia, dementia and hallucinaions

### LINKED ISSUE #181: Add Dementia, Paranoia and Hallucination as focusable afflictions
From http://www.achaea.com/game/news/Achaea/Announce/4539:
> Dementia, Paranoia, and Hallucination afflictions are now focusable afflictions.

### PR DESCRIPTION
**Pull request by keneanung**
Fixes #181

### CODE REVIEW

**Comment by keneanung** [comment]
@vadi2 any comments?

**Comment by vadi2** [comment]
The diff looks good, I'm traveling though and I can't open the entire file
on the phone - do herb cures have a 'not doingaction' on them as well?

**Comment by keneanung** [comment]
Some seem to have and some don't...

**Comment by vadi2** [comment]
Paranoia, dementia, and hallucinations herb checks should so herb cures
don't get sent while the focus cures are pending arrival/processing on the
server.

**Comment by keneanung** [comment]
I see. Will add them then.

**Comment by keneanung** [comment]
@vadi2 Updated this PR with the doingaction check

**Comment by vadi2** [comment]
+1 good work

**Pull request merged**
