### PR TITLE
Changed two-handed focus trigger to use the precision line.

### PR DESCRIPTION
**Pull request by Seifur**
Allows for the proper adding of double stacks when hit with a precision focused attack.

### CODE REVIEW

**Comment by vadi2** [comment]
What about the aggressive stance, is that no longer a thing?

**Comment by Seifur** [comment]
That's focus speed. It only applies one stack per hit.

**Comment by vadi2** [comment]
Could you add a log of diagnose before that line and a diagnose after that line?

**Comment by Seifur** [comment]
I'm just going to close this. Did my own testing this time and no change is necessary. My "helper" earlier told me he had used speed first and then precision. Turns out it was the reverse. I should have just diagnosed instead of taking his word for it.

```
(svo): System paused.
curing off
diagnose
diag
You are:
blind.
deaf.
(p) 10168h, 7566m, 46320e, 34560w xcdbk 57.2-(+19m, 0.3%)
You have recovered equilibrium. (0.975s)
(p) 10168h, 7566m, 46320e, 34560w excdbk 57.2-'ok
Seifur shifts into a more aggressive stance.
Seifur comes around with a terrible swing of a colossal, rune-etched warhammer toward your left leg.
Your leg almost gives out as the hammer crunches brutally into your ankle.
You gasp as your fine-tuned reflexes disappear into a haze of confusion.
(p) 9751h, 7547m, 46320e, 34559w excdbk 57.2-(-417h, 4.1%, -19m, 0.3%)
diagnose
diag
You are:
blind.
deaf.
suffering from 2 torn tendons.
afflicted with clumsiness.
bleeding for 9 health.
(p) 9751h, 7547m, 46320e, 34559w xcdbk 57.2-
```

**Comment by vadi2** [comment]
Now you understand why I've always asked for logs :) thanks for taking the time to look at this

**Pull request closed without merging**
