### PR TITLE
Psion Profile

### PR DESCRIPTION
**Pull request by alex-d-schroder**
Adds defence data and allows for building of a Psion profile for svof. Psion affs and such aren't in yet, only defences.

### CODE REVIEW

**Comment by vadi2** [comment]
Awesome, thank you! Is this ready?

**Comment by alex-d-schroder** [comment]
I've been using it since I made it, it works wonderfully for me. Aralaya has also been using the one I built and uploaded, no complaints from her yet.

**Comment by vadi2** [comment]
Awesome

@keneanung could you look into updating the CI to work?

**Comment by keneanung** [comment]
I kicked it again it's working now (looks like a network fluke)

**Comment by vadi2** [comment]
Sweet... how do we do a new release now?

**Comment by keneanung** [comment]
Creating a tag is enough IIRC. But we should have a look at #385 and possibly merge it first to have two things in the release.

**Comment by vadi2** [comment]
@keneanung could you make a release?

**Comment by keneanung** [comment]
Done. That was more work than I thought since one of the upload places went offline (at least for us) and the machine account lost all API keys...

**Comment by vadi2** [comment]
Thanks for doing it!

**Pull request merged**
