### PR TITLE
Removed charge devil as per issue #146, hydra web as per #148

### PR DESCRIPTION
**Pull request by Ditsypop**
issue #146 ? (:

### CODE REVIEW

**Comment by keneanung** [comment]
Looks correct to me! If Vadi has no objections, I'll merge it soon :)

**Comment by Ditsypop** [comment]
sorry for doing it at separate times I'm a tad drunk and just wanted to get a simple fix out of the way ...

**Comment by bunster** [comment]
Isn't using **sendAll** in an action dangerous? It would spam out in slowcuring mode. Would be safer to make outd'ing items part of the precache... that way it could do something similar to async/sync and only have to send one command at at time.

**Comment by Ditsypop** [comment]
I dunno fam that's kind of out of the scope I was just fixing the minor inconvenience, if u wanna issue it I'll give it a go when I sober up though.

**Comment by vadi2** [comment]
I think this PR is fine - while @bunster's concern is valid, this defence is only really intended to be used in defup, not keepup. Using it in keepup you'd have a chance at screwing yourself over with the system redoing it, unless you've got a good handle on toggling the defence on/off keepup. There's not much reason to be deffing up in aeon either. This would explain this staying fine so long without any complaints.

It could be improved for certain, but chances of it affecting anyone are very small. A separate issue I would say.

**Comment by keneanung** [comment]
I'll merge this in. For the issues raised I created a new issue.

**Comment by keneanung** [comment]
@Ditsypop could you message me in game so I know who to transfer the bounties to?

**Comment by Ditsypop** [comment]
Sure, to double verify, IGN Cesarina, I'll message you from that to confirm that fact.

**Comment by keneanung** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

50 credits transferred to Cesarina in Achaea for this PR.

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQEcBAEBCAAGBQJXD71VAAoJEE34WF2oeolCQ7AH/A73qYAuHInzyyw/COvwsIYT
mhExHHV8eq5h1bHHvv60JuWIPTrqFiKctYcEx1mA30GA2b1dqQ9+mvutdegv2L+4
1KlpgBsuqOzv8BTzNBKxypLzLCzBzDY0MJX5LDSnGAY+5BN6RBaHeqmnvFr31WY9
yuz0pytpSIzh01UEMWDOMTuUzNcpn+9oMx2KikRRIl0M9lOoSmqTLF6QtxxdZBY7
ODKHv+Rts3JB7UiUYlAAW9+f3VkXNMViFX2SMWQgeTDh1KA/w8f9cB35dQdbyQb+
PpOw32US5snEIeWQOVrnZCbFBXtV4GFjrzSJz/tbFhxXaT1RrLYGEwMsyHkDdwM=
=8GKM
-----END PGP SIGNATURE-----

**Comment by Ditsypop** [comment]
Not sure what all that jazz means but I appreciate the credits haha

**Comment by keneanung** [comment]
It's a digital signature.

**Pull request merged**
