### PR TITLE
Changing shroud line to regex

### PR DESCRIPTION
**Pull request by jgh713**
For customised shrouds

### CODE REVIEW

**Comment by keneanung** [comment]
Could this be obsolete with gmcp defs? My plan was to slowly fade def/aff triggers out now.

**Comment by jgh713** [comment]
Will have to code in an exception that defs both shroud AND cloaking for this defup, or they'll need to be combined as per #215 (which should be done anyway, since they're the same), but essentially, yes.

**Comment by jgh713** [comment]
Though, be careful about phasing out those triggers, there's a decent number of things that gmcp doesn't cover adequately.

**Comment by keneanung** [comment]
I do. This is why I want to phase them out instead of deleting them right away.

**Comment by jgh713** [comment]
No longer necessary with a recent change Ken made to dict.sstosvod. Going to close.

**Pull request closed without merging**
