### PR TITLE
Fix possible nil reference to gmcp.Char.Status.race

### PR DESCRIPTION
**Pull request by EldFitheach**

### CODE REVIEW

**Comment by keneanung** [comment]
:+1: looks simple enough. I assumed this kind of check would be necessary, but needed someone to confirm that there was no further issue.

**Comment by vadi2** [comment]
+1

**Comment by keneanung** [comment]
Another thought... Does dragonform stay through log out?

If so, maybe we should skip the whole function if we find no race field, because otherwise we'd first set "no dragon", which sets some things in motion and undo that decision afterwards.

**Comment by vadi2** [comment]
Yes it stays through logout.

**Comment by EldFitheach** [comment]
Yeah, that just occurred to me over my morning coffee. Fixing now.

**Comment by keneanung** [comment]
Renewing my :+1: :smile:

**Comment by QwindorRousseau** [comment]
Is this whole issue dealing with the dragon portion of
gmcp.Char.Status.race?

**Comment by keneanung** [comment]
Um... No? If you read this and the issue it's about an error message that comes up on login and sometimes in between...

**Comment by QwindorRousseau** [comment]
Okie dokie wasnt sure as i couldnt see it all in the email i got.

**Pull request merged**
