### PR TITLE
Fixing osx install instructions

### PR DESCRIPTION
**Pull request by jgh713**
Fixing typo in osx install instructions.

### CODE REVIEW

**Comment by jgh713** [comment]
Perhaps related to #202. Needs more work, because luarocks by default installs those packages to 5.2 install dirs, not 5.1

**Comment by jgh713** [comment]
These instructions seem to work properly.

**Comment by keneanung** [comment]
> Needs more work, because luarocks by default installs those packages to 5.2 install dirs, not 5.1

Is his fixed by installing a recent version of `luarocks`?

**Comment by jgh713** [comment]
@keneanung luarocks searches for your current version of Lua, preferring 5.2 over 5.1. By not installing 5.2, it defaults to 5.1.

**Comment by keneanung** [comment]
What if lua 5.2 is already installed for some reason? Maybe we should give instructions along http://stackoverflow.com/a/20359102?

**Comment by jgh713** [comment]
That's why I added 'brew uninstall lua' to the instructions, but I suppose if they have it installed for another program or some such, that would work better.

**Comment by jgh713** [comment]
Seemed to work fine on my system.

**Comment by keneanung** [comment]
don't you have to change the luarocks command to `luarocks-5.1`?

**Comment by jgh713** [comment]
I actually have no clue how the luarocks command works with different versions. It's just luarocks for 5.1 without 5.2 installed. Will have to look into it.

**Comment by keneanung** [comment]
@jgh713 any updates on this?

**Comment by keneanung** [comment]
All right, I dove a bit more into this. If you install `lua51`, luarocks will be installed automatically as `luarocks-5.1`, so no need to manually install luarocks-5.1, just change the luarocks command. A caveat: 5.2 and 5.1 rocks will overwrite each other. If that's a problem, the --tree option must be given.

**Comment by vadi2** [comment]
No longer needed with upcoming in-client-svof.

**Pull request closed without merging**
