### PR TITLE
Corrected numerous spacing and spelling issues

### PR DESCRIPTION
**Pull request by Seifur**
Medallion was consistently misspelled throughout and I didn't like the extra spacing.

### CODE REVIEW

**Comment by vadi2** [comment]
It's not misspelled: https://de.wikipedia.org/wiki/Medaillon_(Ornament)

@keneanung

**Comment by eewallace** [comment]
The English spelling, which is what Achaea uses, is "medallion". Seems reasonable to adhere to in-game language/spelling conventions where applicable, no?

**Comment by Seifur** [comment]
Was just going by the actual artifact name used in-game.

```
Medallion of Enchantments: 300 credits
   - This will allow you to batch up to 5 conjuration creations.
     The syntax is: BEGIN CREATION OF <1-5> <enchantment>
```

**Comment by vadi2** [comment]
I hadn't checked in-game, I assumed that was the spelling it used in the game. I'd agree with making it use the in-game spelling.

**Pull request merged**
