### PR TITLE
Gmcp anti-illusion failure workaround

### PR DESCRIPTION
**Pull request by jgh713**
Simple workaround for gmcp afflictions and defences failing due to anti-illusion checks.

There's likely a better way to do this already implemented in the system, but this works as-is.

### CODE REVIEW

**Comment by keneanung** [comment]
I'm not aware of afflictions failing due to anti-illusion. Defenses failing is due to the call to "checkaction" in some got_* functions. My personal way to fix it would be https://github.com/svof/svof/compare/master...keneanung:gmcpAillusionFix

**Comment by vadi2** [comment]
That would be a much better solution

**Comment by jgh713** [comment]
Will need to add it to the other got_ function as well. Cant right now, but if it hasnt been done later I add it and test.

**Comment by keneanung** [comment]
Which other `got_ ` function? The one that call only `defences.got`? Not really, because that has no illusion check at all.

**Comment by jgh713** [comment]
Theres two calls for got_, one for gmcpchardefencesadd and one for list. I might have just missed the other one (on kobile right now).

**Comment by keneanung** [comment]
Oh, right, forgot about the list!

**Comment by keneanung** [comment]
Updated my branch for the list as well!

**Comment by jgh713** [comment]
The fix doesn't work properly. There's some anti-illusion failsafe that I'm missing here. Even directly calling defences.got() fails because of aillusion for some reason. No clue why. @vadi2 any insight?

**Comment by keneanung** [comment]
I have some insight. `defs.got_*` adds to the lifevision system, which waits for a prompt before processing. Between gmcp and prompt comes the curing command, which routes through to `killaction()`. This function also removes from the lifevision processing list and thus the gmcp update is lost.

**Comment by keneanung** [comment]
Updated my branch (https://github.com/svof/svof/compare/master...keneanung:gmcpAillusionFix) with something that worked. @jgh713 you want to check it again?

**Comment by jgh713** [comment]
I havent tested your changes yet, but directly calling defences.got () on the defence fails too, which makes me think the problem lies elsewhere. Will test shortly.

**Comment by keneanung** [comment]
I didn't look into the defence.got() part yet, so I probably just didn't catch everything.

**Comment by keneanung** [comment]
> directly calling defences.got () on the defence fails too

I just tested it and it doesn't fail for me (made the `defences` table public for testing and called it via `vlua`, `vshow defs` showed the defences afterwards just fine)

**Pull request merged**
