### PR TITLE
Make Svof reloadable.

### PR DESCRIPTION
**Pull request by macjabeth**
Using the **vreload** alias, it should now be possible to keep the state
and reload the system on the fly to make it easier to edit.

### CODE REVIEW

**Comment by vadi2** [comment]
Where's the keeping the state bit?

**Comment by bunster** [comment]
What do you mean by "keeping the state"? What state is being kept?

**Comment by vadi2** [comment]
Well the description says "it should now be possible to keep the state", which state is it talking about?

**Comment by bunster** [comment]
Keeping the current profile loaded / being able to reload the system.

**Comment by vadi2** [comment]
The system state needs to be kept though, as not everything will initialise the same way out of the blue - it relies on the login messages and GMCP data. For example the character name will be unknown, and that will break some things.

**Comment by bunster** [comment]
I see... Been rattling my brain on an answer to this. One idea could be keeping a list of which files are important to keep synchronised, so before you reload the system, you could save them into another table, and then merge them back in once the system is reloaded. Thoughts?

**Comment by vadi2** [comment]
A general design like that would work, the trick is loading everything back right and initialising things that need initialising.

**Comment by bunster** [comment]
Would something like this work?
```lua
function svo_reload()
  local attrs = {}
  local save_keys = {}
  -- Possibly, if we make a list of important keys:
  --[=[for i = 1, #save_keys do attrs[save_keys[i]] = package.loaded.svo[save_keys[i]] end --]=]
  for key, value in pairs(package.loaded.svo) do
    attrs[key] = value
  end
  package.loaded.svo = nil
  -- loader for packages
  local foldername
  for item in lfs.dir(getMudletHomeDir()) do
    foldername = item:match("(%w+) svo")
    if foldername and lfs.attributes(getMudletHomeDir().."/"..foldername.." svo/svo") then
      local oldpath = package.path
      local system_path = getMudletHomeDir().."/"..foldername.." svo/"
      package.path = system_path .. "?;" .. system_path .. "?.lua;" .. system_path .. "?.dll;" .. system_path .. "?.so;"

      local s,m = pcall(require, "svo")
      package.path = oldpath

      if not s then display(m) return end

      -- The issue would be if we changed/updated something in one of the already defined global tables.
      for key, value in pairs(attrs) do
        svo[key] = value
      end

      svo.echofn("Reloaded & ready to go, version %s (", tostring(svo.version))
      echoLink("homepage", '(openUrl or openURL)"http://svo.vadisystems.com"', "Svo homepage")
      decho(svo.getDefaultColor()..")\n")
      return
    end
  end
end
```

**Comment by vadi2** [comment]
Test it out - reload the system, then run with it for a while - see if
anything breaks.

**Comment by vadi2** [comment]
By the looks of the above you'll be overwriting all new functions with the
old ones, kind of negating reloading.

**Comment by bunster** [comment]
Well sadly that is the only way of doing it, hence adding the save_keys table commented out. If we can make a list (I'm not sure which ones should be sync'd), then we can uncomment out that method instead.

**Comment by vadi2** [comment]
Yep, it's not trivial, that's why it's not in yet as a feature.

**Comment by keneanung** [comment]
Don't mind me, only marking connection wth #3

**Comment by keneanung** [comment]
@bunster any updates on this?

**Comment by vadi2** [comment]
Closing it in favour of https://github.com/svof/svof/pull/329, which makes Svof reloadable without losing the system state.

**Pull request closed without merging**
