### PR TITLE
Add defensive support against depthswalker

### PR DESCRIPTION
**Pull request by keneanung**
See #238 (a?) list of new afflictions.

Scope of this PR:
- [x] Track Degenerate
- [x] Track Depression
- [x] Track Deteriorate
- [x] Track Hatred
- [x] Track Parasite
- [x] Track Retribution
- [x] Track Shadowmadness
- [x] Track Timeloop
- [x] Track Paradox
- [x] Trigger Shadowmancy cull for the "fighting depthswalker" tracking
- [x] Trigger Shadowmancy reap for the "fighting depthswalker" tracking
- [x] Trigger Shadowmancy strike for the "fighting depthswalker" tracking

### CODE REVIEW

**Comment by vadi2** [comment]
Missing entries in simple.lua and main.lua (for generic and tree curing if any), I think.

**Comment by vadi2** [comment]
Dev readme was incomplete, [I've updated it](https://github.com/svof/svof/pull/242). Need to add to the system that handles passive and blackout cures too.

**Comment by keneanung** [comment]
I added basic paradox tracking. It might be prone to illusions right now and breaks when you log in with paradox still on you, but I'd like to get the testing release out and take care of that in the next circle.

cc: @vadi2 @jgh713

**Comment by vadi2** [comment]
I'm not able to test but I had a look through the commit and it looks good
from the coding looks good.

**Pull request merged**
