### PR TITLE
Clearing unknown affs on empty tree

### PR DESCRIPTION
**Pull request by jgh713**

### CODE REVIEW

**Comment by jgh713** [comment]
Marking #165

**Comment by vadi2** [comment]
Tree doesn't cure all affs though.

**Comment by jgh713** [comment]
@vadi2

I was under the impression that pretty much all random affs were treeable. Is this not the case?

And if that isn't the case, why does treeable contain unknownany/unknownmental?

**Comment by jgh713** [comment]
Also, should any2 and any3 treeable strategies consider multiple unknownmental or unknownany as treeable? At current, no matter how many of one you have, it's considered one.

**Comment by jgh713** [comment]
Still have a few denizens to test, but as far as I can tell all unknownany are treeable, and all but one unknownmental affs are focusable.

**Comment by keneanung** [comment]
@vadi2 @jgh713 what's the status on this?

**Comment by vadi2** [comment]
Seems like a safe assumption to make though confusing the semantics even if they happen to align right now is not a good idea. I don't mind either way, just commented

**Pull request merged**
