### PR TITLE
Inker Changes

### PR DESCRIPTION
**Pull request by tsartin**
1. allows limb arguments
2. adds auto reinking toggle for interrupted tattoos

### CODE REVIEW

**Comment by tsartin** [comment]
1) Allows limb arguments in inker as requested in #695
Note that it works for the syntaxes:

ink boar 
ink boar on person 
ink boar on limb of person

But does NOT work for the syntax:

ink boar on left arm (which normally does work on yourself in game)

I'm not sure how to add that and not conflict with 'ink boar on person'.

If accepted the documentation should also be updated. (I'm not sure how to change the documentation)

**Comment by tsartin** [comment]
2) Default was to always reink interrupted tattoos which could be frustrating.

This just adds an option to turn that off.

The proposed option would be 'vconfig autoreink'

**Review by vadi2 — APPROVED** [review]

**Comment by TheLastDarkthorne** [comment]
> 1. Allows limb arguments in inker as requested in [Tattoo Inker does not accept a limb argument  #695](https://github.com/svof/svof/issues/695)
>    Note that it works for the syntaxes:
> 
> ink boar ink boar on person ink boar on limb of person
> 
> But does NOT work for the syntax:
> 
> ink boar on left arm (which normally does work on yourself in game)
> 
> I'm not sure how to add that and not conflict with 'ink boar on person'.
> 
> If accepted the documentation should also be updated. (I'm not sure how to change the documentation)

You can probably make a table with all acceptable limb parts and check the match against it. If it is not a limb part, assume it is a person then?

**Comment by TheLastDarkthorne** [comment]
Also to edit the docs you just go in the docs folder and commit an edit to the respective doc files in your branch

**Comment by tsartin** [comment]
> > 1. Allows limb arguments in inker as requested in [Tattoo Inker does not accept a limb argument  #695](https://github.com/svof/svof/issues/695)
> >    Note that it works for the syntaxes:
> > 
> > ink boar ink boar on person ink boar on limb of person
> > But does NOT work for the syntax:
> > ink boar on left arm (which normally does work on yourself in game)
> > I'm not sure how to add that and not conflict with 'ink boar on person'.
> > If accepted the documentation should also be updated. (I'm not sure how to change the documentation)
> 
> You can probably make a table with all acceptable limb parts and check the match against it. If it is not a limb part, assume it is a person then?

That's a good idea. I had actually thought about something similar then I got stuck on the actual match. Currently it looks for "(%w+)$" but it needs to match ' one or two words then end of line'  🤔

**Comment by TheLastDarkthorne** [comment]
@tsartin `local anotherperson = order:match(" on (%w+)$") or order:match(" of (%w+)$")`
The problem with this is that it will also match 'ink boar of person' for example, not that anyone would deliberately do that but I don't think it is a proper way to handle the problem... 
You can probably change the regex to account for multiple words (like .+)  and then check it against a table of bodyparts?

EDIT: Actually I think there might be a better way to handle this which is to change the alias regex to something less greedy... I will see if I can come up with something

**Comment by TheLastDarkthorne** [comment]
Could try changing the alias regex to this, lookie:
https://regexr.com/6diud

This way, you only need to handle the matches instead of the whole string, much better! (I think)

**Comment by tsartin** [comment]
> a better way to handle this which is to change the alias regex to something less greedy... I will see if I can come up with something

I think I prefer this too.  If someone does 'ink boar' there's not a whole lot the inker adds over the in-game inker anyway. 

Then do we just do check on group 2? Like if group two is not a limb then it's a person?

**Comment by TheLastDarkthorne** [comment]
> > a better way to handle this which is to change the alias regex to something less greedy... I will see if I can come up with something
> 
> I think I prefer this too. If someone does 'ink boar' there's not a whole lot the inker adds over the in-game inker anyway.
> 
> Then do we just do check on group 2? Like if group two is not a limb then it's a person?

Yup! :)

**Pull request merged**
