### PR TITLE
A fix for the ndb alias cheatsheet erroring out

### PR DESCRIPTION
**Pull request by ndsamuelson**
I am uncertain WHY it was erroring every time, but in order to make this function this was the only solution I could find to the problem.

### CODE REVIEW

**Comment by keneanung** [comment]
This will break the cheat sheet for developers, who don't install svof as a package.

**Comment by ndsamuelson** [comment]
Well, I'm just not sure what is causing the script to return nil for f when that code is in there. It may break the cheatsheet for developers, but for the everyday user who needs it more I would say that it would better serve everyone if we could figure it out. I'll mess with it tomorrow when I have more time

**Comment by keneanung** [comment]
It will use this part only if the normal location is not found. Maybe we should find out why this is the case.

Are you using a recent svof? Do you use the correct class package?

**Comment by ndsamuelson** [comment]
I am using the most updated version. My mudlet home dir just for your info is... C:\Users\Nic_2\.config\mudlet\profiles\Colg clean\

I'm messing with it right now to see if I can solve it. As it stands right now it's not working again. So I went back to the original code to try and find a reason f returns nil on line 49.

**Comment by ndsamuelson** [comment]
Going to make a correct pull request. Sorry for the confusion. I'm new here :)

**Pull request closed without merging**
