### PR TITLE
Add depthswalker class package and defenses

### PR DESCRIPTION
**Pull request by keneanung**
Adds support for the new depthswalker class defenses.

See #238 

- [x] Add shadowcloak
- [x] add disperse
- [x] add shadowveil
- [x] add chrono blur
- [x] add word balance tracking
- [x] add age tracking
- [x] add Trusad
- [x] add Tsuura
- [x] add Ukhia
- [x] add Qamad
- [x] add Mainaas
- [x] add Gaiartha

Optional:
- [ ] Implement `med` equivalent for dilation
- [ ] add Kail

### CODE REVIEW

**Comment by jgh713** [comment]
Age needs illusion/lag handling similar to other balances.

**Comment by keneanung** [comment]
@jgh713 There you go. I wouldn't say age tracking is a balance, but a resource, which is why I implemented it slightly different.

**Comment by keneanung** [comment]
@jgh713 I believe we are done for this circle, don't you think?

**Comment by jgh713** [comment]
Looks like.

On Nov 22, 2016 5:01 PM, keneanung <notifications@github.com> wrote:

@jgh713<https://github.com/jgh713> I believe we are done for this circle, don't you think?

**Pull request merged**
