### PR TITLE
Azdun slug slashed throat/illness trigger

### PR DESCRIPTION
**Pull request by Seifur**
Azdun slug slashed throat/illness bashing trigger.

I'm not sure if there's female slugs down there. All I saw was the line with "He" in it. I included a "She" line just in case.

Hopefully this is enough context:
```
You may eat another plant or mineral. (2.938s) (1.645s)
[ex] 5860h, 6138m, 99%e, 97%w [cdbk] [slug] [20:15:56.992] [??]
You are:
blind.
deaf. (11.153s)
[x] 5860h, 6138m, 99%e, 97%w [cdbk] [slug] [20:15:57.104] gut slug
You must regain equilibrium first.
[x] 5860h, 6138m, 99%e, 97%w [cdbk] [slug] [20:15:57.476] 
 -------------------------------------------
|     EQUILIBRIUM BACK | EQUILIBRIUM BACK   |
 -------------------------------------------
You may eat another bit of irid moss or potash. (0.98s) (5.877s)
[ex] 5860h, 6138m, 99%e, 97%w [cdbk] [slug] [20:15:58.084] 
A flesh-eating slug lets out a high-pitched shriek and begins to boil madly. He releases 
noxious fumes, causing you to gag and vomit uncontrollably.
You are confused as to the effects of the venom.
[ex] 5053h[-807h], 6138m, 99%e, 97%w [cdbk] [slug] [20:15:58.232] [lac1 ? ill]
You take out some salve and quickly rub it on your head.
The bleeding gash in your throat closes up completely. (0.083s)
[ex] 5053h, 6138m, 99%e, 97%w [cdbk] [slug] [20:15:58.314] [? ill]
You eat a ferrum flake.
Your stomach becalms itself. (0.171s)
[ex] 5053h, 6138m, 99%e, 97%w [cdbk] [slug] [20:15:58.402] [?]
You remove 1 ferrum, bringing the total in the Rift to 2075.
[ex] 5053h, 6138m, 99%e, 97%w [cdbk] [slug] [20:15:58.414] [?]gut slug
You rip into a flesh-eating slug with your massive, deadly claws.
You have scored a CRITICAL hit!
[Rage]: +5.5. Total: 31.5 Now Available: Dragonfear
[e] 5053h, 6138m, 99%e, 97%w [cdbk] [slug] [20:15:58.772] [?]
You may apply another salve to yourself. (0.947s)
[e] 5053h, 6138m, 99%e, 97%w [cdbk] [slug] [20:15:59.260] [?]
You may eat another plant or mineral. (1.541s)
[e] 5053h, 6138m, 99%e, 97%w [cdbk] [slug] [20:15:59.943] [?]
You may drink another health or mana elixir. (4.49s)
[e] 5053h, 6138m, 99%e, 97%w [cdbk] [slug] [20:16:01.114] [?]
You take a drink from a black-walnut vial.
The elixir heals and soothes you.
[e] 6315h[+1262h], 6138m, 99%e, 97%w [cdbk] [slug] [20:16:01.212] [?]
A flesh-eating slug lets out a high-pitched shriek and begins to boil madly. He releases 
noxious fumes, causing you to gag and vomit uncontrollably.
You are confused as to the effects of the venom.
[e] 5504h[-811h], 6138m, 99%e, 97%w [cdbk] [slug] [20:16:01.288] [lac1 ?? ill]
You take out some salve and quickly rub it on your head.
The bleeding gash in your throat closes up completely. (0.141s)
[e] 5856h[+352h], 6138m, 99%e, 97%w [cdbk] [slug] [20:16:01.428] [?? ill]
You eat a ferrum flake.
Your stomach becalms itself. (0.204s)
[e] 5856h, 6138m, 99%e, 97%w [cdbk] [slug] [20:16:01.491] [??]
You remove 1 ferrum, bringing the total in the Rift to 2074.
[e] 5856h, 6138m, 99%e, 97%w [cdbk] [slug] [20:16:01.502] [??]
 ------------------------------------- 
|     BALANCE BACK | BALANCE BACK     |
 -------------------------------------  (3.016s)
[ex] 5856h, 6138m, 99%e, 97%w [cdbk] [slug] [20:16:01.788] [??]
You are:
blind.
deaf.
overcome by dizziness.(new) (3.667s)
[x] 5856h, 6138m, 99%e, 97%w [cdbk] [slug] [20:16:01.898] [diz]
```

### CODE REVIEW

**Comment by vadi2** [comment]
There should also be a function where you can say that you've seen a symptom of an affliction, so the unknown aff gets replaced by a symptom. Try using that in combination with what you've got, so you don't end up with an unknown aff from the loki.

It's not documented in the Svo public API as people previously had no need to worry about triggers being out of date - probably should be now.

**Comment by Seifur** [comment]
Isn't that already done with the group of triggers named "Symptoms"?

**Comment by vadi2** [comment]
Yes, it is, for symptoms - unrelated to the issue at hand. Notice how after all of that, there is a **?** left in the prompt? That shouldn't be there, because you know what afflictions you've got.

**Comment by eewallace** [comment]
Does that attack *only* give slashed throat and nausea, or is there an additional loki aff? The 
"You are confused as to the effects of the venom." implies the latter, and that would explain the dizziness in the last diagnose. The log is still weird, since there's two loki lines and only one untracked aff, but it might make sense if one of the loki procs was nausea.

**Comment by Seifur** [comment]
Yes, it gives lacerated throat, illness, and loki. The loki is covered by the 'You are confused as to the effects of the venom.' line. There's a trigger already that calls `svo.valid.simpleunknownany()` for that line.

**Comment by keneanung** [comment]
Am I missing something why this is not merged yet? The diff looks valid and if Loki can double up, this might explain the missing aff.

**Comment by vadi2** [comment]
It can be merged

**Pull request merged**
