### PR TITLE
Change documentation theme for Sphinx

### PR DESCRIPTION
**Pull request by keneanung**
See http://keneanung.github.io/svof/ for the result

### CODE REVIEW

**Comment by keneanung** [comment]
This will fix #43

**Comment by vadi2** [comment]
Hm the TOC for the addons is replicated three times, twice in the sidebar and once in the main content, could you fix that?

**Comment by keneanung** [comment]
Have a look now? I updated my GitHub.io version.

**Comment by vadi2** [comment]
+1

**Pull request merged**
