### PR TITLE
A (hopefully) viable way to fix the ndb alias

### PR DESCRIPTION
**Pull request by ndsamuelson**
Added a way to check which route the script took. I tested on my end and it seems to work. I don't run a dev version though so I can't test that side.

### CODE REVIEW

**Comment by ndsamuelson** [comment]
And I have no idea why travis-ci is erroring out. Or really what travis-ci is even. Heh.

**Comment by keneanung** [comment]
Travis is a tool which runs our (minimalist) integration tests. Them failing isn't your fault though (in this case). Looks like a tool we use updated its dependencies and one of those uses a ruby version that is not installed by default.

**Comment by ndsamuelson** [comment]
Well that's good. Glad it wasn't my fail coding heh

**Comment by ndsamuelson** [comment]
I have confirmed that this fixes the problem at least for those not using a dev version of svof. Can someone try it on the dev version to make sure it works properly?

**Comment by keneanung** [comment]
I opened an alternative PR (#224) with the actually preferred way to go. But this PR got me on the right track. Thank you very much :+1:

**Pull request closed without merging**
